# Generated by Django 4.1 on 2022-09-24 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cities", "0003_alter_city_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Train name"
                    ),
                ),
                (
                    "from_city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cities.city",
                        verbose_name="From which city",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Train",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Train name"
                    ),
                ),
                (
                    "travel_time",
                    models.PositiveSmallIntegerField(verbose_name="Travel time"),
                ),
                (
                    "from_city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="from_city_set",
                        to="cities.city",
                        verbose_name="From which city",
                    ),
                ),
                (
                    "to_city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="to_city_set",
                        to="cities.city",
                        verbose_name="To which city",
                    ),
                ),
            ],
            options={
                "verbose_name": "Train",
                "verbose_name_plural": "Trains",
                "ordering": ["travel_time"],
            },
        ),
    ]
