# Generated by Django 4.1 on 2022-09-30 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("trains", "0002_alter_traintest_from_city"),
        ("cities", "0003_alter_city_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Route name"
                    ),
                ),
                (
                    "travel_time",
                    models.PositiveSmallIntegerField(
                        verbose_name="General travel time"
                    ),
                ),
                (
                    "from_city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="route_from_city_set",
                        to="cities.city",
                        verbose_name="From which city",
                    ),
                ),
                (
                    "to_city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="route_to_city_set",
                        to="cities.city",
                        verbose_name="To which city",
                    ),
                ),
                (
                    "trains",
                    models.ManyToManyField(
                        to="trains.train", verbose_name="List of trains"
                    ),
                ),
            ],
            options={
                "verbose_name": "Route",
                "verbose_name_plural": "Routes",
                "ordering": ["travel_time"],
            },
        ),
    ]
