# Generated by Django 4.1 on 2022-09-24 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cities", "0002_alter_city_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="name",
            field=models.CharField(max_length=100, unique=True, verbose_name="Name"),
        ),
    ]
